In [5]:
import pandas as pd

df = pd.read_csv("/content/spotify_2015_2025_85k.csv")
type(df)

df.head()

,track_id,track_name,artist_name,album_name,release_date,genre,duration_ms,popularity,danceability,energy,key,loudness,mode,instrumentalness,tempo,stream_count,country,explicit,label
0,TRK-BEBD53DA84E1,Agent every (0),Noah Rhodes,Beautiful instead,2016-04-01,Pop,234194,55,0.15,0.74,9,-32.22,0,0.436,73.12,13000,Brazil,0,Universal Music
1,TRK-6A32496762D7,Night respond,Jennifer Cole,Table,2022-04-15,Metal,375706,45,0.44,0.46,0,-14.02,0,0.223,157.74,1000,France,1,Island Records
2,TRK-47AA7523463E,Future choice whatever,Brandon Davis,Page southern,2016-02-23,Rock,289191,55,0.62,0.80,8,-48.26,1,0.584,71.03,1000,Germany,1,XL Recordings
3,TRK-25ADA22E3B06,Bad fall pick those,Corey Jones,Spring,2015-10-12,Pop,209484,51,0.78,0.98,1,-34.47,1,0.684,149.00,1000,France,0,Warner Music
4,TRK-9245F2AD996A,Husband,Mark Diaz,Great prove,2022-07-08,Indie,127435,39,0.74,0.18,10,-17.84,0,0.304,155.85,2000,United States,0,Independent

In [6]:
#reshaping data, 가장 인기가 많은 노래 top10 을 뽑아보자

df.sort_values('popularity' , ascending=False). head(n=10)

,track_id,track_name,artist_name,album_name,release_date,genre,duration_ms,popularity,danceability,energy,key,loudness,mode,instrumentalness,tempo,stream_count,country,explicit,label
74669,TRK-07A69363B197,Growth task,Jeremiah Cox,Learn,2016-04-27,Pop,191943,100,0.80,0.65,2,-21.43,1,0.411,192.84,20000000,Mexico,0,EMI
6713,TRK-A828991F3648,Sit write,Mark Ray,Smile,2015-09-14,R&B,416424,100,0.86,0.25,5,-27.26,1,0.734,196.73,686000,Australia,1,Sony Music
74713,TRK-FEA90F422154,Ten,Tamara Santiago,Drug,2017-12-19,EDM,176090,100,0.69,0.55,6,-6.43,1,0.746,66.50,725000,Japan,0,Sony Music
1481,TRK-69BC500A0237,Upon,Monica Kim,Shake statement,2015-10-01,R&B,239443,100,0.66,0.04,1,-52.31,0,0.185,140.49,20000000,Brazil,0,XL Recordings
37883,TRK-5707F5B2139A,Reveal close news suggest write,Natasha Leon,Member story,2024-09-25,R&B,160864,100,0.94,0.46,5,-15.79,1,0.616,193.60,116000,Canada,0,EMI
30025,TRK-9E3B7DC5A4CB,View place,Bonnie Kim,Day,2023-01-24,Classical,401755,100,0.22,0.41,7,-30.20,0,0.349,109.83,7488000,Canada,0,Warner Music
65560,TRK-2FD9B61303C8,Energy best myself,Jillian Stephenson,Nearly,2015-10-30,Folk,151481,100,0.63,0.28,5,-51.80,1,0.357,84.79,20000000,Australia,0,Sony Music
76975,TRK-77E157D58CE2,Home rather,Colton Roberts,Agency,2015-04-16,Indie,124519,100,0.52,0.62,1,-24.86,1,0.437,188.38,7452000,Japan,0,Island Records
5149,TRK-CBC29A83F9D7,Against recently,Edward Ramirez,Per event,2025-05-19,Hip-Hop,195654,100,0.49,0.71,7,-5.63,0,0.253,149.73,20000000,Germany,0,Columbia
48379,TRK-10239FA42BA2,Which identify feel,Ryan King,There effect,2022-12-15,Jazz,320290,100,0.77,0.63,1,-16.79,0,0.006,81.90,20000000,United Kingdom,0,Warner Music

In [7]:

#생각보다 100이 많으니까 popularity가 100인 곡 수가 얼마나 많은지 알아보자
(df['popularity'] == 100).sum()
len(df[df['popularity'] == 100])
#397개가 있다고 나온다.

397

In [8]:
#인기가 가장 많은 곡들의 장르와 국가를 보고 싶음

df[df['popularity'] == 100]['genre'].value_counts()
#힙합이 가장 많음

genre
Hip-Hop      44
Pop          40
R&B          39
Metal        38
Folk         37
Classical    34
Rock         31
Jazz         31
EDM          29
Country      27
Indie        25
Reggaeton    22
Name: count, dtype: int64

In [9]:
df[df['popularity'] == 100]['country'].value_counts()
# 캐나다 일본, 멕시코 등등등

country
Canada            49
Japan             48
Mexico            44
United Kingdom    41
India             41
Germany           38
United States     37
Brazil            36
France            33
Australia         30
Name: count, dtype: int64

In [37]:
#group by 함수를 이용해서 인기가 가장 많은 곡들의 장르와 국가의 조합들을 보고 싶음
df.groupby(['genre', 'country'])['popularity'].mean().sort_values(ascending=False)

genre      country
R&B        Brazil       49.825215
Hip-Hop    Brazil       49.456311
Country    Brazil       49.298883
Pop        France       49.255350
Folk       Japan        49.193681
                          ...
Rock       Germany      47.047091
Country    India        46.995726
Indie      Brazil       46.822254
Reggaeton  Australia    46.743440
Country    Mexico       46.479638
Name: popularity, Length: 120, dtype: float64

In [10]:
from numpy import column_stack
#생각보다 인사이트 이끌어내는 게 어렵다.. GPT 도움이 필요하니 column 명을 추출해보자
df.columns

Index(['track_id', 'track_name', 'artist_name', 'album_name', 'release_date',
       'genre', 'duration_ms', 'popularity', 'danceability', 'energy', 'key',
       'loudness', 'mode', 'instrumentalness', 'tempo', 'stream_count',
       'country', 'explicit', 'label'],
      dtype='object')

In [11]:
df[['popularity', 'danceability', 'energy', 'tempo']].corr()

# correlation, 상관관계를 분석해보자
#popularity랑 danceability랑은 양의 상관관계인데 다른 것들은 아니다.

              popularity  danceability    energy     tempo
popularity      1.000000      0.003193 -0.000378 -0.002763
danceability    0.003193      1.000000 -0.004136 -0.002584
energy         -0.000378     -0.004136  1.000000 -0.006582
tempo          -0.002763     -0.002584 -0.006582  1.000000

In [12]:
#popularity랑 explicit의 상관관계도 알아보자
df[['popularity', 'explicit']].corr()
#음의 상관관계

            popularity  explicit
popularity    1.000000 -0.000903
explicit     -0.000903  1.000000

In [13]:
#자극적인 곡의 인기도를 살펴보자
df[df['explicit'] == 1]['popularity'].value_counts()
#보통 40점대의 인기도를 가짐
df_explicit = df[df['explicit'] == 1].sort_values(by='popularity', ascending=False)
df_explicit

,track_id,track_name,artist_name,album_name,release_date,genre,duration_ms,popularity,danceability,energy,key,loudness,mode,instrumentalness,tempo,stream_count,country,explicit,label
12312,TRK-5991BCDD07B4,Reach let,Stephen Mitchell,Tough,2016-10-21,Metal,331364,100,0.43,0.50,1,-13.98,1,0.149,80.88,20000000,United Kingdom,1,Sony Music
21244,TRK-CDC1DC19DA2B,Positive picture,Lindsey Brown,Practice growth,2020-05-03,Rock,369939,100,0.88,0.52,8,-30.36,1,0.395,157.36,20000000,Japan,1,Universal Music
8679,TRK-DB44DCE84E1C,Western magazine nature force fire,Angela Lowe MD,Miss,2025-06-15,Reggaeton,329380,100,0.34,0.53,3,-13.97,1,0.664,116.00,20000000,India,1,EMI
49450,TRK-4C647F07C43F,Common carry,Anna Campbell,Fund,2017-05-30,R&B,133507,100,0.11,0.10,1,-50.44,1,0.621,140.18,934000,Mexico,1,Universal Music
39156,TRK-FBC4E3C6CD56,Attention name herself film,Morgan Cross,Marriage Republican,2024-01-13,Country,263602,100,0.70,0.61,9,-47.97,1,0.330,74.74,2320000,Canada,1,XL Recordings
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31725,TRK-BBCDD5A86B83,Usually today property check,Paula Thompson,Western,2022-06-20,Metal,403606,7,0.57,0.99,7,-17.71,1,0.290,73.77,2000,France,1,Warner Music
37606,TRK-695839BB779C,Pull PM,Karla Lynch,Actually,2022-08-12,Metal,161675,7,0.60,0.49,5,-22.61,0,0.573,175.72,1000,Mexico,1,Warner Music
44311,TRK-9A8A31CE503C,North,Brooke Smith,Per position,2023-02-22,Rock,229270,5,0.92,0.64,11,-12.40,0,0.039,87.15,1000,Brazil,1,Warner Music
25067,TRK-4E5A6FBE5DA5,Model indicate sort,Julie George,Answer,2025-11-30,Hip-Hop,291439,2,0.49,0.81,4,-42.80,0,0.440,106.77,1000,Brazil,1,Universal Music
65811,TRK-9D068B7CC180,Finish of staff tell piece,Elizabeth Miller,Get,2025-07-23,Metal,259821,0,0.82,0.74,2,-8.06,0,0.171,110.13,1000,Japan,1,Columbia

In [15]:
#레게톤 중에 인기가 있는 것의 특징을 알아보자
df_Reggaeton = df[(df['genre'] == 'Reggaeton') & (df['popularity'] == 100)]

In [27]:
len(df['genre'] == 'Reggaeton')

85000

In [32]:
df_Reggaeton_NP = df[(df['genre'] == 'Reggaeton') & (df['popularity'] < 50)]
len(df_Reggaeton_NP)

4131

In [33]:
df_Reggaeton_P = df[(df['genre'] == 'Reggaeton') & (df['popularity'] >= 50)]
len(df_Reggaeton_P)

2870

In [30]:
df_Reggaeton_NP.mean(numeric_only=True)

duration_ms         254017.675623
popularity              38.376664
danceability             0.520487
energy                   0.506664
key                      5.563544
loudness               -28.168891
mode                     0.509562
instrumentalness         0.398237
tempo                  130.346383
stream_count          3532.800775
explicit                 0.198257
dtype: float64

In [34]:
df_Reggaeton_P.mean(numeric_only=True)

duration_ms         253166.002439
popularity              61.562369
danceability             0.524686
energy                   0.505470
key                      5.504530
loudness               -27.615237
mode                     0.491289
instrumentalness         0.404016
tempo                  129.628697
stream_count        453458.188153
explicit                 0.200697
dtype: float64

In [35]:
#유의미한 차이가 있는 행이 없는 것으로..

#어떤 나라에서 스트리밍이 많이 나오나?

df.groupby('country')['stream_count'].mean().sort_values(ascending=False)

country
Japan             234555.814495
France            230021.264166
Mexico            227466.298873
United Kingdom    221028.139040
Canada            217595.359629
Germany           213475.382996
India             208233.051339
Brazil            206665.606596
United States     192909.547739
Australia         191027.450980
Name: stream_count, dtype: float64

In [36]:
df[['duration_ms', 'popularity']].corr()

             duration_ms  popularity
duration_ms     1.000000   -0.000556
popularity     -0.000556    1.000000