In [19]:
import pandas as pd

df = pd.read_csv("/spotify_2015_2025_85k.csv")
type(df)

df.head()

,track_id,track_name,artist_name,album_name,release_date,genre,duration_ms,popularity,danceability,energy,key,loudness,mode,instrumentalness,tempo,stream_count,country,explicit,label
0,TRK-BEBD53DA84E1,Agent every (0),Noah Rhodes,Beautiful instead,2016-04-01,Pop,234194,55,0.15,0.74,9,-32.22,0,0.436,73.12,13000,Brazil,0,Universal Music
1,TRK-6A32496762D7,Night respond,Jennifer Cole,Table,2022-04-15,Metal,375706,45,0.44,0.46,0,-14.02,0,0.223,157.74,1000,France,1,Island Records
2,TRK-47AA7523463E,Future choice whatever,Brandon Davis,Page southern,2016-02-23,Rock,289191,55,0.62,0.80,8,-48.26,1,0.584,71.03,1000,Germany,1,XL Recordings
3,TRK-25ADA22E3B06,Bad fall pick those,Corey Jones,Spring,2015-10-12,Pop,209484,51,0.78,0.98,1,-34.47,1,0.684,149.00,1000,France,0,Warner Music
4,TRK-9245F2AD996A,Husband,Mark Diaz,Great prove,2022-07-08,Indie,127435,39,0.74,0.18,10,-17.84,0,0.304,155.85,2000,United States,0,Independent

In [20]:
#reshaping data, 가장 인기가 많은 노래 top10 을 뽑아보자

df.sort_values('popularity' , ascending=False). head(n=10)

,track_id,track_name,artist_name,album_name,release_date,genre,duration_ms,popularity,danceability,energy,key,loudness,mode,instrumentalness,tempo,stream_count,country,explicit,label
74669,TRK-07A69363B197,Growth task,Jeremiah Cox,Learn,2016-04-27,Pop,191943,100,0.80,0.65,2,-21.43,1,0.411,192.84,20000000,Mexico,0,EMI
6713,TRK-A828991F3648,Sit write,Mark Ray,Smile,2015-09-14,R&B,416424,100,0.86,0.25,5,-27.26,1,0.734,196.73,686000,Australia,1,Sony Music
74713,TRK-FEA90F422154,Ten,Tamara Santiago,Drug,2017-12-19,EDM,176090,100,0.69,0.55,6,-6.43,1,0.746,66.50,725000,Japan,0,Sony Music
1481,TRK-69BC500A0237,Upon,Monica Kim,Shake statement,2015-10-01,R&B,239443,100,0.66,0.04,1,-52.31,0,0.185,140.49,20000000,Brazil,0,XL Recordings
37883,TRK-5707F5B2139A,Reveal close news suggest write,Natasha Leon,Member story,2024-09-25,R&B,160864,100,0.94,0.46,5,-15.79,1,0.616,193.60,116000,Canada,0,EMI
30025,TRK-9E3B7DC5A4CB,View place,Bonnie Kim,Day,2023-01-24,Classical,401755,100,0.22,0.41,7,-30.20,0,0.349,109.83,7488000,Canada,0,Warner Music
65560,TRK-2FD9B61303C8,Energy best myself,Jillian Stephenson,Nearly,2015-10-30,Folk,151481,100,0.63,0.28,5,-51.80,1,0.357,84.79,20000000,Australia,0,Sony Music
76975,TRK-77E157D58CE2,Home rather,Colton Roberts,Agency,2015-04-16,Indie,124519,100,0.52,0.62,1,-24.86,1,0.437,188.38,7452000,Japan,0,Island Records
5149,TRK-CBC29A83F9D7,Against recently,Edward Ramirez,Per event,2025-05-19,Hip-Hop,195654,100,0.49,0.71,7,-5.63,0,0.253,149.73,20000000,Germany,0,Columbia
48379,TRK-10239FA42BA2,Which identify feel,Ryan King,There effect,2022-12-15,Jazz,320290,100,0.77,0.63,1,-16.79,0,0.006,81.90,20000000,United Kingdom,0,Warner Music

In [12]:

#생각보다 100이 많으니까 popularity가 100인 곡 수가 얼마나 많은지 알아보자
(df['popularity'] == 100).sum()
len(df[df['popularity'] == 100])
#397개가 있다고 나온다.

397

In [17]:
#group by 함수를 이용해서 인기가 가장 많은 곡들의 장르와 국가를 보고 싶음

df[df['popularity'] == 100]['genre'].value_counts()
#힙합이 가장 많음

genre
Hip-Hop      44
Pop          40
R&B          39
Metal        38
Folk         37
Classical    34
Rock         31
Jazz         31
EDM          29
Country      27
Indie        25
Reggaeton    22
Name: count, dtype: int64

In [18]:
df[df['popularity'] == 100]['country'].value_counts()
# 캐나다 일본, 멕시코 등등등

country
Canada            49
Japan             48
Mexico            44
United Kingdom    41
India             41
Germany           38
United States     37
Brazil            36
France            33
Australia         30
Name: count, dtype: int64

In [26]:
from numpy import column_stack
#생각보다 인사이트 이끌어내는 게 어렵다.. GPT 도움이 필요하니 column 명을 추출해보자
df.columns

Index(['track_id', 'track_name', 'artist_name', 'album_name', 'release_date',
       'genre', 'duration_ms', 'popularity', 'danceability', 'energy', 'key',
       'loudness', 'mode', 'instrumentalness', 'tempo', 'stream_count',
       'country', 'explicit', 'label'],
      dtype='object')

In [27]:
df[['popularity', 'danceability', 'energy', 'tempo']].corr()

# correlation, 상관관계를 분석해보

              popularity  danceability    energy     tempo
popularity      1.000000      0.003193 -0.000378 -0.002763
danceability    0.003193      1.000000 -0.004136 -0.002584
energy         -0.000378     -0.004136  1.000000 -0.006582
tempo          -0.002763     -0.002584 -0.006582  1.000000